import axios from "axios";
import React, { createContext } from "react";
import { useEffect } from "react";
import { useState } from "react";

const districts = [
  "Dhaka", "Gazipur", "Kishoreganj", "Manikganj", "Munshiganj", "Narayanganj",
  "Narsingdi", "Rajbari", "Shariatpur", "Tangail", "Faridpur", "Gopalganj",
  "Madaripur", "Bandarban", "Brahmanbaria", "Chandpur", "Chattogram",
  "Cox's Bazar", "Cumilla", "Feni", "Khagrachhari", "Lakshmipur", "Noakhali",
  "Rangamati", "Bagerhat", "Chuadanga", "Jashore", "Jhenaidah", "Khulna",
  "Kushtia", "Magura", "Meherpur", "Narail", "Satkhira", "Barguna", "Barishal",
  "Bhola", "Jhalokati", "Patuakhali", "Pirojpur", "Bogura", "Joypurhat",
  "Naogaon", "Natore", "Chapainawabganj", "Pabna", "Rajshahi", "Sirajganj",
  "Dinajpur", "Gaibandha", "Kurigram", "Lalmonirhat", "Nilphamari", "Panchagarh",
  "Rangpur", "Thakurgaon", "Jamalpur", "Mymensingh", "Netrokona", "Sherpur",
  "Habiganj", "Moulvibazar", "Sunamganj", "Sylhet"
];

const upazillas = [
  "Abhaynagar",
  "Adamdighi",
  "Aditmari",
  "Agailjhara",
  "Ajmiriganj",
  "Akhaura",
  "Akkelpur",
  "Alamdanga",
  "Alfadanga",
  "Alikadam",
  "Amtali",
  "Anwara",
  "Araihazar",
  "Ashuganj",
  "Assasuni",
  "Atgharia",
  "Atpara",
  "Atrai",
  "Austagram",
  "Atwari",
  "Babuganj",
  "Badalgachhi",
  "Badarganj",
  "Bagatipara",
  "Bagha",
  "Baghaichhari",
  "Bagherpara",
  "Bagmara",
  "Bagerhat Sadar",
  "Bahubal",
  "Bajitpur",
  "Bakerganj",
  "Bakshiganj",
  "Balaganj",
  "Baliadangi",
  "Baliakandi",
  "Bamna",
  "Bandar",
  "Bandarban Sadar",
  "Banaripara",
  "Bancharampur",
  "Baniyachong",
  "Baraigram",
  "Barguna Sadar",
  "Barkal",
  "Barlekha",
  "Barhatta",
  "Barishal Sadar",
  "Barura",
  "Basail",
  "Banshkhali",
  "Batiaghata",
  "Bauphal",
  "Beanibazar",
  "Begumganj",
  "Belaichhari",
  "Belabo",
  "Belkuchi",
  "Bera",
  "Betagi",
  "Bhadarganj",
  "Bhairab",
  "Bhaluka",
  "Bhanga",
  "Bhangura",
  "Bhandaria",
  "Bheramara",
  "Bholahat",
  "Bhola Sadar",
  "Bhuapur",
  "Bijoynagar",
  "Birampur",
  "Birganj",
  "Biral",
  "Bishwambarpur",
  "Biswanath",
  "Bochaganj",
  "Boda",
  "Boalkhali",
  "Boalmari",
  "Bogura Sadar",
  "Brahmanpara",
  "Brahmanbaria Sadar",
  "Burhanuddin",
  "Burichang",
  "Chakaria",
  "Chandanaish",
  "Chandina",
  "Chandpur Sadar",
  "Chapainawabganj Sadar",
  "Char Fasson",
  "Char Rajibpur",
  "Charbhadrasan",
  "Charghat",
  "Chatkhil",
  "Chatmohar",
  "Chauhali",
  "Chauddagram",
  "Chhatak",
  "Chilmari",
  "Chirirbandar",
  "Chitalmari",
  "Chowgacha",
  "Chuadanga Sadar",
  "Chunarughat",
  "Companiganj (Noakhali)",
  "Companiganj (Sylhet)",
  "Cox's Bazar Sadar",
  "Cumilla Adarsha Sadar",
  "Cumilla Sadar Dakshin",
  "Dacope",
  "Daganbhuiyan",
  "Damudya",
  "Damurhuda",
  "Dasar",
  "Dashmina",
  "Daudkandi",
  "Daulatkhan",
  "Daulatpur (Kushtia)",
  "Daulatpur (Manikganj)",
  "Debhata",
  "Debidwar",
  "Debiganj",
  "Delduar",
  "Derai",
  "Dewanganj",
  "Dhamoirhat",
  "Dhamrai",
  "Dhanbari",
  "Dharamapasha",
  "Dhobaura",
  "Dighalia",
  "Dighinala",
  "Dimla",
  "Dinajpur Sadar",
  "Dohar",
  "Domar",
  "Dowarabazar",
  "Dumki",
  "Dumuria",
  "Dhunat",
  "Dhupchanchia",
  "Durgapur (Netrokona)",
  "Durgapur (Rajshahi)",
  "Eidgaon",
  "Fakirhat",
  "Faridganj",
  "Faridpur",
  "Faridpur Sadar",
  "Fatikchhari",
  "Fenchuganj",
  "Fulbari (Dinajpur)",
  "Fulbari (Kurigram)",
  "Fulbaria",
  "Fulchhari",
  "Fulgazi",
  "Fulpur",
  "Phultala",
  "Gabtali",
  "Gaffargaon",
  "Gaibandha Sadar",
  "Galachipa",
  "Gangachara",
  "Gangni",
  "Gaurnadi",
  "Gazaria",
  "Gazipur Sadar",
  "Ghatail",
  "Ghior",
  "Ghoraghat",
  "Godagari",
  "Goalanda",
  "Gobindaganj",
  "Golapganj",
  "Gomostapur",
  "Gopalganj Sadar",
  "Gopalpur",
  "Gosairhat",
  "Gouripur",
  "Gowainghat",
  "Gurudaspur",
  "Habiganj Sadar",
  "Haimchar",
  "Hajiganj",
  "Hakimpur",
  "Haluaghat",
  "Harinakunda",
  "Haripur",
  "Harirampur",
  "Hatibandha",
  "Hathazari",
  "Hatiya",
  "Hizla",
  "Homna",
  "Hossainpur",
  "Indurkani",
  "Islampur",
  "Ishwardi",
  "Iswarganj",
  "Itna",
  "Jagannathpur",
  "Jaintiapur",
  "Jajira",
  "Jaldhaka",
  "Jamalganj",
  "Jamalpur Sadar",
  "Jashore Sadar",
  "Jhalokati Sadar",
  "Jhenaigati",
  "Jhenaidah Sadar",
  "Jhikargachha",
  "Jibannagar",
  "Joypurhat Sadar",
  "Juri",
  "Juraichhari",
  "Kabirhat",
  "Kachua (Bagerhat)",
  "Kachua (Chandpur)",
  "Kahaloo",
  "Kalia",
  "Kaliakair",
  "Kaliganj (Gazipur)",
  "Kaliganj (Jhenaidah)",
  "Kaliganj (Lalmonirhat)",
  "Kaliganj (Satkhira)",
  "Kalihati",
  "Kalkini",
  "Kalmakanda",
  "Kalukhali",
  "Kamalganj",
  "Kamalnagar",
  "Kamarkhanda",
  "Kanaighat",
  "Kapasia",
  "Kaptai",
  "Karimganj",
  "Karnaphuli",
  "Kashiani",
  "Kasba",
  "Kathalia",
  "Katiadi",
  "Kawkhali (Pirojpur)",
  "Kawkhali (Rangamati)",
  "Kaunia",
  "Kazipur",
  "Kendua",
  "Keraniganj",
  "Keshabpur",
  "Khagrachhari Sadar",
  "Khaliajuri",
  "Khansama",
  "Khetlal",
  "Khoksa",
  "Khulna Sadar",
  "Kishoreganj",
  "Kishoreganj Sadar",
  "Kotchandpur",
  "Kotalipara",
  "Koyra",
  "Kulaura",
  "Kuliarchar",
  "Kumarkhali",
  "Kurigram Sadar",
  "Kushtia Sadar",
  "Kutubdia",
  "Lakhai",
  "Laksam",
  "Lakshmichhari",
  "Lakshmipur Sadar",
  "Lalmai",
  "Lalmohan",
  "Lalmonirhat Sadar",
  "Lalpur",
  "Lama",
  "Langadu",
  "Lohagara (Chattogram)",
  "Lohagara (Narail)",
  "Lohajang",
  "Madan",
  "Madarganj",
  "Madaripur Sadar",
  "Madhabpur",
  "Madhukhali",
  "Madhupur",
  "Magura Sadar",
  "Mahadevpur",
  "Mahalchhari",
  "Maheshkhali",
  "Maheshpur",
  "Manda",
  "Manikchhari",
  "Manikganj Sadar",
  "Manirampur",
  "Manpura",
  "Mathbaria",
  "Matiranga",
  "Matlab Dakshin",
  "Matlab Uttar",
  "Meghna",
  "Mehendiganj",
  "Meherpur Sadar",
  "Melandaha",
  "Mirpur",
  "Mirsarai",
  "Mirzaganj",
  "Mirzapur",
  "Mithamain",
  "Mithapukur",
  "Mohammadpur",
  "Mohanganj",
  "Mohanpur",
  "Mollahat",
  "Mongla",
  "Monohardi",
  "Monohargonj",
  "Morelganj",
  "Moulvibazar Sadar",
  "Muksudpur",
  "Muktagachha",
  "Muladi",
  "Munshiganj Sadar",
  "Muradnagar",
  "Mujibnagar",
  "Mymensingh Sadar",
  "Nabiganj",
  "Nabinagar",
  "Nachole",
  "Nagarpur",
  "Nageshwari",
  "Nagarkanda",
  "Naikhongchhari",
  "Naldanga",
  "Nalitabari",
  "Nalchity",
  "Nandail",
  "Nandigram",
  "Nangalkot",
  "Naniarchar",
  "Narail Sadar",
  "Narayanganj Sadar",
  "Naria",
  "Narsingdi Sadar",
  "Nasirnagar",
  "Natore Sadar",
  "Nawabganj (Dhaka)",
  "Nawabganj (Dinajpur)",
  "Nazirpur",
  "Nesarabad (Swarupkati)",
  "Netrokona Sadar",
  "Niamatpur",
  "Nikli",
  "Nilphamari Sadar",
  "Noakhali Sadar",
  "Osmani Nagar",
  "Paba",
  "Pabna Sadar",
  "Paikgachha",
  "Pakundia",
  "Palash",
  "Palashbari",
  "Panchagarh Sadar",
  "Panchbibi",
  "Panchhari",
  "Pangsha",
  "Parbatipur",
  "Parshuram",
  "Patharghata",
  "Patiya",
  "Patgram",
  "Patuakhali Sadar",
  "Patnitala",
  "Pekua",
  "Pirgachha",
  "Pirganj (Rangpur)",
  "Pirganj (Thakurgaon)",
  "Pirojpur Sadar",
  "Porsha",
  "Purbadhala",
  "Puthia",
  "Raiganj",
  "Raipura",
  "Raipur",
  "Rajapur",
  "Rajbari Sadar",
  "Rajoir",
  "Rajnagar",
  "Rajasthali",
  "Rajshahi Sadar",
  "Ramu",
  "Rampur",
  "Rangabali",
  "Rangamati Sadar",
  "Rangunia",
  "Raninagar",
  "Ranisankail",
  "Raozan",
  "Rajarhat",
  "Rowmari",
  "Rowangchhari",
  "Ruma",
  "Rupganj",
  "Rupsha",
  "Sadarpur",
  "Sadullapur",
  "Saidpur",
  "Sakhipur",
  "Saltha",
  "Sandwip",
  "Santhia",
  "Sapahar",
  "Sarail",
  "Sariakandi",
  "Sarishabari",
  "Sarankhola",
  "Satkania",
  "Satkhira Sadar",
  "Saturia",
  "Savar",
  "Senbagh",
  "Shahrasti",
  "Shahjadpur",
  "Shahjahanpur",
  "Shailkupa",
  "Shantiganj",
  "Shariatpur Sadar",
  "Sharsha",
  "Sherpur",
  "Sherpur Sadar",
  "Shibalaya",
  "Shibchar",
  "Shibganj (Bogura)",
  "Shibganj (Chapainawabganj)",
  "Shibpur",
  "Shyamnagar",
  "Singair",
  "Singra",
  "Sirajdikhan",
  "Sirajganj Sadar",
  "Sitakunda",
  "Sonagazi",
  "Sonaimuri",
  "Sonargaon",
  "Sonatala",
  "Sreebardi",
  "Sreemangal",
  "Sreenagar",
  "Sreepur (Gazipur)",
  "Sreepur (Magura)",
  "Subarnachar",
  "Sujanagar",
  "Sughatta",
  "Sullah",
  "Sundarganj",
  "Sunamganj Sadar",
  "Sylhet Sadar",
  "Tahirpur",
  "Tala",
  "Taltali",
  "Tangail Sadar",
  "Tanore",
  "Taraganj",
  "Tarail",
  "Tarash",
  "Tazumuddin",
  "Teknaf",
  "Terokhada",
  "Tetulia",
  "Thakurgaon Sadar",
  "Thanchi",
  "Titas",
  "Tongibari",
  "Trishal",
  "Tungipara",
  "Ukhiya",
  "Ullahpara",
  "Ulipur",
  "Wazirpur",
  "Zakiganj"
]

const bloodgroups = [
  "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"
];

export const ThemeContext = createContext();

export const ThemeProvider = ({ children }) => {
  const api = 'https://bloodcampus-server.onrender.com/api'
  const base_url = 'https://bloodcampus-server.onrender.com'
  const [donors, setDonors] = useState([]);
    const [notification, setNotification] = useState(null)
  const [loading, setLoading] = useState(true);
  const [user, setUser] = useState([])
  const [isLogin, setIsLogin] = useState(false)
  const [isAdmin, setIsAdmin] = useState(false)

  useEffect(() => {
    const fetchServer = async () => {
      try {
        const response = await axios.get(`${base_url}`, { withCredentials: true })
        if (response.data.success) {
          setLoading(false)

        }
      } catch (error) {
        setLoading(true)
        setNotification('Failed to load server')

      }
    }
    fetchServer()
  }, [])

  useEffect(() => {
    const fetchDonors = async () => {
      try {
        const response = await axios.get(`${api}/user`, { withCredentials: true })
        setDonors(response.data.payload)

      } catch (error) {
        console.log(error?.response?.data?.message || 'Failed to fetch user')

      }
    };

    fetchDonors();
  }, []);


  useEffect(() => {
    const fetchUser = async () => {
      try {
        const response = await axios.get(`${api}/user/protected`, { withCredentials: true })
        console.log(response.data.message)
        if (response.data.success) {
          setIsLogin(true)
          setUser(response.data.payload)
          if (response.data.payload.isAdmin) {
            setIsAdmin(true)
          } else {
            setIsAdmin(false)
          }
        } else {
          setIsAdmin(false)
          setIsLogin(false)
          setUser([])
        }

      } catch (error) {
        console.log(error?.response?.data?.message || 'Failed to authenticate user')

      }
    }
    fetchUser()
  }, [])

  const contextValue = {
    districts,upazillas, bloodgroups, donors, setDonors, loading, api,
    user, setUser, isAdmin, setIsAdmin, isLogin, setIsLogin,notification, setNotification

  }


  return (
    <ThemeContext.Provider value={contextValue}>
      {children}
    </ThemeContext.Provider>
  );
};
